# 中文 Navigation Menu
[menu]
  [[menu.main]]
    name = "功能"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "性能", url = "/features/performance/" },
        { name = "设计系统", url = "/features/design-system/" },
        { name = "开发体验", url = "/features/developer-experience/" }
      ]

  [[menu.main]]
    name = "价格"
    url = "/pricing/"
    weight = 2

  [[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    name = "公司"
    weight = 4
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "关于我们", url = "/company/" },
        { name = "招聘", url = "/careers/" }
      ]